<?php

namespace ContainerJx2Tpdx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_CfjZy82Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.CfjZy82' shared service.
     *
     * @return \App\Controller\LoggerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\HomeController::repost()": the $logger argument is type-hinted with the non-existent class or interface: "App\\Controller\\LoggerInterface". Did you forget to add a use statement?');
    }
}
