<?php

namespace ContainerJx2Tpdx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T97wOIeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T97wOIe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T97wOIe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.fcP3Ord', 'get_ServiceLocator_FcP3OrdService', true],
            'App\\Controller\\HomeController::repost' => ['privates', '.service_locator.T2dSDBg', 'get_ServiceLocator_T2dSDBgService', true],
            'App\\Controller\\PostController::like' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PostController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PostController::repost' => ['privates', '.service_locator.OgZEEkX', 'get_ServiceLocator_OgZEEkXService', true],
            'App\\Controller\\UserController::follow' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserProfileController::index' => ['privates', '.service_locator.fcP3Ord', 'get_ServiceLocator_FcP3OrdService', true],
            'App\\Controller\\loginControlleur::login' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\loginControlleur::register' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.fcP3Ord', 'get_ServiceLocator_FcP3OrdService', true],
            'App\\Controller\\HomeController:repost' => ['privates', '.service_locator.T2dSDBg', 'get_ServiceLocator_T2dSDBgService', true],
            'App\\Controller\\PostController:like' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PostController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PostController:repost' => ['privates', '.service_locator.OgZEEkX', 'get_ServiceLocator_OgZEEkXService', true],
            'App\\Controller\\UserController:follow' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserProfileController:index' => ['privates', '.service_locator.fcP3Ord', 'get_ServiceLocator_FcP3OrdService', true],
            'App\\Controller\\loginControlleur:login' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\loginControlleur:register' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::repost' => '?',
            'App\\Controller\\PostController::like' => '?',
            'App\\Controller\\PostController::new' => '?',
            'App\\Controller\\PostController::repost' => '?',
            'App\\Controller\\UserController::follow' => '?',
            'App\\Controller\\UserProfileController::index' => '?',
            'App\\Controller\\loginControlleur::login' => '?',
            'App\\Controller\\loginControlleur::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:repost' => '?',
            'App\\Controller\\PostController:like' => '?',
            'App\\Controller\\PostController:new' => '?',
            'App\\Controller\\PostController:repost' => '?',
            'App\\Controller\\UserController:follow' => '?',
            'App\\Controller\\UserProfileController:index' => '?',
            'App\\Controller\\loginControlleur:login' => '?',
            'App\\Controller\\loginControlleur:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
