# Définir la route de connexion
login:
    path: /login
    controller: App\Controller\SecurityController::login

# Redirection vers la page de login
login_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: login

new_post:
    path: /post/new
    controller: App\Controller\PostController::new

post_like:
    path: /post/{id}/like
    controller: App\Controller\PostController::like
    methods: POST

post_repost:
    path: /post/{id}/repost
    controller: App\Controller\PostController::repost
    methods: POST

user_profile:
    path: /user/profile/{id}
    controller: App\Controller\UserProfileController::index

user_follow:
    path: /user/{id}/follow
    controller: App\Controller\UserController::followUser
    methods: POST