# Définir la route de connexion
login:
    path: /login
    controller: App\Controller\SecurityController::login

# Redirection vers la page de login
login_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: login

new_post:
    path: /post/new
    controller: App\Controller\PostController::new