# index:
#    path: /
#    controller: App\Controller\DefaultController::index

# home:
#     path: /
#     controller: App\Controller\HomeController::index

login_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: login
