<?php

namespace ContainerQxgDNWs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T2dSDBgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T2dSDBg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T2dSDBg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', '.errored.CfjZy82', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::repost()": the $logger argument is type-hinted with the non-existent class or interface: "App\\Controller\\LoggerInterface". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.0vOlWP4', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::repost()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'logger' => '?',
            'request' => '?',
        ]);
    }
}
