<?php

namespace ContainerH2H93Ng;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_REAGSXWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.REAGSXW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.REAGSXW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'postRepository' => ['privates', '.errored.Km8FOaL', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $postRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PostRepository".'],
        ], [
            'postRepository' => '?',
        ]);
    }
}
