<?php

namespace ContainerH2H93Ng;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YWJIHg5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yWJIHg5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yWJIHg5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.REAGSXW', 'get_ServiceLocator_REAGSXWService', true],
            'App\\Controller\\HomeController::indexPosts' => ['privates', '.service_locator.TVJLHCp', 'get_ServiceLocator_TVJLHCpService', true],
            'App\\Controller\\loginControlleur::login' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\loginControlleur::register' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.REAGSXW', 'get_ServiceLocator_REAGSXWService', true],
            'App\\Controller\\HomeController:indexPosts' => ['privates', '.service_locator.TVJLHCp', 'get_ServiceLocator_TVJLHCpService', true],
            'App\\Controller\\loginControlleur:login' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\loginControlleur:register' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::indexPosts' => '?',
            'App\\Controller\\loginControlleur::login' => '?',
            'App\\Controller\\loginControlleur::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:indexPosts' => '?',
            'App\\Controller\\loginControlleur:login' => '?',
            'App\\Controller\\loginControlleur:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
