<?php

namespace ContainerH2H93Ng;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_YG41tLwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.yG41tLw' shared service.
     *
     * @return \App\Repository\PostRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\HomeController::indexPosts()": the $postRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PostRepository".');
    }
}
