<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS7ibl5F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS7ibl5F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS7ibl5F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS7ibl5F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS7ibl5F\App_KernelDevDebugContainer([
    'container.build_hash' => 'S7ibl5F',
    'container.build_id' => '7bed0504',
    'container.build_time' => 1744387930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS7ibl5F');
