<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH2H93Ng\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH2H93Ng/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH2H93Ng.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH2H93Ng\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH2H93Ng\App_KernelDevDebugContainer([
    'container.build_hash' => 'H2H93Ng',
    'container.build_id' => 'a238d85f',
    'container.build_time' => 1744277181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH2H93Ng');
