<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUOCtKQt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUOCtKQt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUOCtKQt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUOCtKQt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUOCtKQt\App_KernelDevDebugContainer([
    'container.build_hash' => 'UOCtKQt',
    'container.build_id' => '99a0c76e',
    'container.build_time' => 1744839805,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUOCtKQt');
